/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef GSANCMCUPSTREAMCHANNELTABLE_H
#define GSANCMCUPSTREAMCHANNELTABLE_H

/* function declarations */
void InitGsAnCmcUsChannelTable(void);

/* column number definitions for table gsAnCmcUpstreamChannelTable */
#define ColCmcUpChanId 1
#define ColCmcUpChanErrRate 2
#define ColCmcUpChanSnr 3
#define ColCmcUpChanName 4
#define ColCmcUpChanEnable 5
#define ColCmcUpChanActiveCmCount 6
#define ColCmcUpChanRegisterCmCount 7
#define ColCmcUpChanUnregisterCmCount 8
#define ColCmcUpChanInputPower 9

Netsnmp_Node_Handler CmcUsChannelTableHandler;
Netsnmp_First_Data_Point CmcUsChannelTableGetFirst;
Netsnmp_Next_Data_Point CmcUsChannelTableGetNext;

#endif /* GSANCMCUPSTREAMCHANNELTABLE_H */
