/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 17337 2009-01-01 14:28:29Z
 */
#ifndef _gsDslAddress_h_
#define _gsDslAddress_h_

/* function declarations */
void InitGsDslAddress(void);
int HandleGsDslOutBandIpAddress(netsnmp_mib_handler *handler,
    netsnmp_handler_registration *reginfo,
    netsnmp_agent_request_info   *reqinfo,
    netsnmp_request_info         *requests);

int HandleGsDslOutBandIpMask(netsnmp_mib_handler *handler,
    netsnmp_handler_registration *reginfo,
    netsnmp_agent_request_info   *reqinfo,
    netsnmp_request_info         *requests);

int HandleGsDslOutBandMACAddress(netsnmp_mib_handler *handler,
    netsnmp_handler_registration *reginfo,
    netsnmp_agent_request_info   *reqinfo,
    netsnmp_request_info         *requests);

int HandleGsDslInBandMACAddress(netsnmp_mib_handler *handler,
    netsnmp_handler_registration *reginfo,
    netsnmp_agent_request_info   *reqinfo,
    netsnmp_request_info         *requests);

#endif /* _gsDslAddress_h_ */
