/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 17337 2009-01-01 14:28:29Z magfr $
 */
#include "SystemInclude.h"
#include "BcmController.h"

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "SystemInfoMgt.h"
#include "gsDslAddress.h"

using namespace std;

/** Initializes the gsDslAddress module */
void InitGsDslAddress(void)
{
    const oid gsDslOutBandIpAddressOid[] = { 1,3,6,1,4,1,22764,7900,3,1,8,1 };
    const oid gsDslOutBandIpMaskOid[] = { 1,3,6,1,4,1,22764,7900,3,1,8,2 };
    const oid gsDslOutBandMACAddressOid[] = { 1,3,6,1,4,1,22764,7900,3,1,8,3 };
    const oid gsDslInBandMACAddressOid[] = { 1,3,6,1,4,1,22764,7900,3,1,8,4 };

    netsnmp_handler_registration* handler;

    handler = netsnmp_create_handler_registration("gsDslOutBandIpAddress",
        HandleGsDslOutBandIpAddress,
        gsDslOutBandIpAddressOid, OID_LENGTH(gsDslOutBandIpAddressOid),
        HANDLER_CAN_RWRITE);
    netsnmp_register_scalar(handler);

    handler = netsnmp_create_handler_registration("gsDslOutBandIpMask",
        HandleGsDslOutBandIpMask,
        gsDslOutBandIpMaskOid, OID_LENGTH(gsDslOutBandIpMaskOid),
        HANDLER_CAN_RWRITE);
    netsnmp_register_scalar(handler);

    handler = netsnmp_create_handler_registration("gsDslOutBandMACAddress",
        HandleGsDslOutBandMACAddress,
        gsDslOutBandMACAddressOid, OID_LENGTH(gsDslOutBandMACAddressOid),
        HANDLER_CAN_RWRITE);
    netsnmp_register_scalar(handler);

    handler = netsnmp_create_handler_registration("gsDslInBandMACAddress",
        HandleGsDslInBandMACAddress,
        gsDslInBandMACAddressOid, OID_LENGTH(gsDslInBandMACAddressOid),
        HANDLER_CAN_RWRITE);
    netsnmp_register_scalar(handler);
}

int HandleGsDslOutBandIpAddress(netsnmp_mib_handler *handler,
    netsnmp_handler_registration *reginfo,
    netsnmp_agent_request_info   *reqinfo,
    netsnmp_request_info         *requests)
{
    struct in_addr ip;
    switch(reqinfo->mode)
    {
    case MODE_GET:
        if (GetIntfAddrInfo("eth0", &ip, NULL, NULL) != BASE_OK)
        {
            return SNMP_ERR_GENERR;
        }
        snmp_set_var_typed_value(requests->requestvb, ASN_IPADDRESS,
            &ip.s_addr, sizeof(uint32_t));
        break;

    default:
        /* we should never get here, so this is a really bad error */
        snmp_log(LOG_ERR, "unknown mode (%d) in HandleGsDslOutBandIpAddress\n",
            reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int HandleGsDslOutBandIpMask(netsnmp_mib_handler *handler,
    netsnmp_handler_registration *reginfo,
    netsnmp_agent_request_info   *reqinfo,
    netsnmp_request_info         *requests)
{
    struct in_addr mask;
    switch (reqinfo->mode)
    {
    case MODE_GET:
        if (GetIntfAddrInfo("vlan1", NULL, &mask, NULL) != BASE_OK)
        {
            return SNMP_ERR_GENERR;
        }
        snmp_set_var_typed_value(requests->requestvb, ASN_IPADDRESS,
            &mask.s_addr, sizeof(uint32_t));
        break;

    default:
        /* we should never get here, so this is a really bad error */
        snmp_log(LOG_ERR, "unknown mode (%d) in HandleGsDslOutBandIpMask\n",
            reqinfo->mode);
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int HandleGsDslOutBandMACAddress(netsnmp_mib_handler *handler,
    netsnmp_handler_registration *reginfo,
    netsnmp_agent_request_info   *reqinfo,
    netsnmp_request_info         *requests)
{
    uint8_t mac[6];
    switch(reqinfo->mode)
    {
    case MODE_GET:
        if (GetIntfAddrInfo("vlan1", NULL, NULL, mac) != BASE_OK)
        {
            return SNMP_ERR_GENERR;
        }
        snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
            mac, 6);
        break;

    default:
        /* we should never get here, so this is a really bad error */
        snmp_log(LOG_ERR, "unknown mode (%d) in HandleGsDslOutBandMACAddress\n",
            reqinfo->mode);
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int HandleGsDslInBandMACAddress(netsnmp_mib_handler *handler,
    netsnmp_handler_registration *reginfo,
    netsnmp_agent_request_info   *reqinfo,
    netsnmp_request_info         *requests)
{
    uint8_t mac[6];
    switch(reqinfo->mode)
    {
    case MODE_GET:
        if (GetIntfAddrInfo("eth0", NULL, NULL, mac) != BASE_OK)
        {
            return SNMP_ERR_GENERR;
        }
        snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
            mac, 6);
        break;

    default:
        /* we should never get here, so this is a really bad error */
        snmp_log(LOG_ERR, "unknown mode (%d) in HandleGsDslOutBandMACAddress\n",
            reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
