/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 17337 2009-01-01 14:28:29Z magfr $
 */

#include "SystemInclude.h"
#include "BcmController.h"

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "Debug.h"
#include "SystemInfoMgt.h"
#include "system.h"

using namespace std;

/** Initializes the system module */
void InitSystem(void)
{
    const oid sysDescrOid[]    = { 1,3,6,1,2,1,1,1 };
    const oid sysObjectIdOid[] = { 1,3,6,1,2,1,1,2 };
    const oid sysUpTimeOid[]   = { 1,3,6,1,2,1,1,3 };
    const oid sysContactOid[]  = { 1,3,6,1,2,1,1,4 };
    const oid sysNameOid[]     = { 1,3,6,1,2,1,1,5 };
    const oid sysLocationOid[] = { 1,3,6,1,2,1,1,6 };
    const oid sysServicesOid[] = { 1,3,6,1,2,1,1,7 };
    //const oid sysORLastChangeOid[] = { 1,3,6,1,2,1,1,8 };

    netsnmp_handler_registration* handler;

    handler = netsnmp_create_handler_registration("sysDescr", HandleSystemDescr,
        sysDescrOid, OID_LENGTH(sysDescrOid), HANDLER_CAN_RONLY);
    netsnmp_register_scalar(handler);

    handler = netsnmp_create_handler_registration("sysObjectID", HandleSystemObjectId,
        sysObjectIdOid, OID_LENGTH(sysObjectIdOid), HANDLER_CAN_RONLY);
    netsnmp_register_scalar(handler);

    handler = netsnmp_create_handler_registration("sysUpTime", HandleSystemUpTime,
        sysUpTimeOid, OID_LENGTH(sysUpTimeOid), HANDLER_CAN_RONLY);
    netsnmp_register_scalar(handler);

    handler = netsnmp_create_handler_registration("sysContact", HandleSystemContact,
        sysContactOid, OID_LENGTH(sysContactOid), HANDLER_CAN_RWRITE);
    netsnmp_register_scalar(handler);

    handler = netsnmp_create_handler_registration("sysName", HandleSystemName,
        sysNameOid, OID_LENGTH(sysNameOid), HANDLER_CAN_RWRITE);
    netsnmp_register_scalar(handler);

    handler = netsnmp_create_handler_registration("sysLocation", HandleSystemLocation,
        sysLocationOid, OID_LENGTH(sysLocationOid), HANDLER_CAN_RWRITE);
    netsnmp_register_scalar(handler);

    handler = netsnmp_create_handler_registration("sysServices", HandleSystemServices,
        sysServicesOid, OID_LENGTH(sysServicesOid), HANDLER_CAN_RONLY);
    netsnmp_register_scalar(handler);
}

int HandleSystemDescr(netsnmp_mib_handler *handler,
    netsnmp_handler_registration *reginfo,
    netsnmp_agent_request_info   *reqinfo,
    netsnmp_request_info         *requests)
{
    const size_t MaxSysDescrLen = 256;
    char sysDescr[MaxSysDescrLen];
    switch(reqinfo->mode)
    {
    case MODE_GET:
        GetSystemDescr(sysDescr, MaxSysDescrLen);
        snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
            sysDescr, strlen(sysDescr));
        break;

    default:
        /* we should never get here, so this is a really bad error */
        snmp_log(LOG_ERR, "unknown mode (%d) in HandleSystemDescr\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int HandleSystemObjectId(netsnmp_mib_handler *handler,
    netsnmp_handler_registration *reginfo,
    netsnmp_agent_request_info   *reqinfo,
    netsnmp_request_info         *requests)
{
    const oid SystemObjectId[] = {1,3,6,1,4,1,22764,1015,9026};
    switch(reqinfo->mode)
    {
    case MODE_GET:
        snmp_set_var_typed_value(requests->requestvb, ASN_OBJECT_ID,
            SystemObjectId, sizeof(SystemObjectId));
        break;

    default:
        /* we should never get here, so this is a really bad error */
        snmp_log(LOG_ERR, "unknown mode (%d) in HandleSystemObjectID\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int HandleSystemUpTime(netsnmp_mib_handler *handler,
    netsnmp_handler_registration *reginfo,
    netsnmp_agent_request_info   *reqinfo,
    netsnmp_request_info         *requests)
{
    switch(reqinfo->mode)
    {
    case MODE_GET:
        snmp_set_var_typed_integer(requests->requestvb, ASN_TIMETICKS,
            netsnmp_get_agent_uptime());
        break;

    default:
        /* we should never get here, so this is a really bad error */
        snmp_log(LOG_ERR, "unknown mode (%d) in HandleSystemObjectID\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int HandleSystemContact(netsnmp_mib_handler *handler,
    netsnmp_handler_registration *reginfo,
    netsnmp_agent_request_info   *reqinfo,
    netsnmp_request_info         *requests)
{
    const size_t MaxSysContractLen = 256;
    char sysContract[MaxSysContractLen];
    switch(reqinfo->mode)
    {
    case MODE_GET:
        GetSystemContact(sysContract, MaxSysContractLen);
        snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
            sysContract, strlen(sysContract));
        break;

    default:
        /* we should never get here, so this is a really bad error */
        snmp_log(LOG_ERR, "unknown mode (%d) in HandleSystemContact\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int HandleSystemName(netsnmp_mib_handler *handler,
    netsnmp_handler_registration *reginfo,
    netsnmp_agent_request_info   *reqinfo,
    netsnmp_request_info         *requests)
{
    const size_t MaxSysNameLen = 256;
    char sysName[MaxSysNameLen];
    switch(reqinfo->mode)
    {
    case MODE_GET:
        GetSystemName(sysName, MaxSysNameLen);
        snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
            sysName, strlen(sysName));
        break;

    default:
        /* we should never get here, so this is a really bad error */
        snmp_log(LOG_ERR, "unknown mode (%d) in HandleSystemName\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int HandleSystemLocation(netsnmp_mib_handler *handler,
    netsnmp_handler_registration *reginfo,
    netsnmp_agent_request_info   *reqinfo,
    netsnmp_request_info         *requests)
{
    const size_t MaxSysLocationLen = 256;
    char sysLocation[MaxSysLocationLen];
    switch(reqinfo->mode)
    {
    case MODE_GET:
        GetSystemLocation(sysLocation, MaxSysLocationLen);
        snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
            sysLocation, strlen(sysLocation));
        break;

    default:
        /* we should never get here, so this is a really bad error */
        snmp_log(LOG_ERR, "unknown mode (%d) in HandleSystemLocation\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

int HandleSystemServices(netsnmp_mib_handler *handler,
    netsnmp_handler_registration *reginfo,
    netsnmp_agent_request_info   *reqinfo,
    netsnmp_request_info         *requests)
{
    int services;
    switch(reqinfo->mode)
    {
    case MODE_GET:
        services = GetSystemServices();
        snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
            &services, sizeof(int));
        break;

    default:
        /* we should never get here, so this is a really bad error */
        snmp_log(LOG_ERR, "unknown mode (%d) in HandleSystemServices\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}



