WorkspaceRoot=$(shell FindRootPath.sh $(CURDIR))
include $(WorkspaceRoot)/Make/Make.Configuration

SubDirs = gsAnCmcNotifications gsAnCmcObjects

all: $(SubDirs)
include $(WorkspaceRoot)/Make/Make.SubDirs

