/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef GSCABLEDOCSUSSPECTRUMSYSTEM_H
#define GSCABLEDOCSUSSPECTRUMSYSTEM_H

/* function declarations */
void InitGsCableDocsUsSpectrumSystem(void);

#if defined(__cplusplus)
extern "C"
{
#endif  //#if defined(__cplusplus)
       
Netsnmp_Node_Handler HandleGsCableDocsUsSpectrumFFTAveraging;

#if defined(__cplusplus)
}
#endif  //#if defined(__cplusplus)

#endif /* GSCABLEDOCSUSSPECTRUMSYSTEM_H */
