/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef _gsAnCmcCmUniTable_h_
#define _gsAnCmcCmUniTable_h_

namespace Snmp
{
namespace GsAnCmcCmUniTalbe
{
/* function declarations */
void InitGsAnCmcCmUniTable(void);
       
Netsnmp_Node_Handler GsAnCmcCmUniTableHandler;
Netsnmp_First_Data_Point GsAnCmcCmUniTableGetFirst;
Netsnmp_Next_Data_Point GsAnCmcCmUniTableGetNext;

/* column number definitions for table gsAnCmcCmUniTable */
#define ColCmUserMacAddr 1
#define ColCmUserIpAddrType 2
#define ColCmUserIpAddr 3
#define ColCmConnectState 4
#define ColCmOnlineTime 5
#define ColCmDocsisVersion 6
#define ColCmTimeOffSet 7
#define ColCmMicroReflect 8
#define ColCmPrimaryUsChannel	9
#define ColCmPrimaryDsChannel 10
#define ColCmUsSNR 11
#define ColCmUsPower 12
#define ColCmDsSNR 13
#define ColCmDsPower 14
#define ColCmNumberOfCPEs 15
#define ColCmConfigFile 16
#define ColCmResetNow 17
#define ColCmDeleteNow 18
#define ColCmUsBandWidth 19
#define ColCmDsBandWidth 20

} /* namespace GsAnCmcCmUniTalbe*/
} /* namespace Snmp*/

#endif /* _gsAnCmcCmUniTable_h_ */
