/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef GSANCMCCMCPETABLE_H
#define GSANCMCCMCPETABLE_H

/* function declarations */
void InitGsAnCmcCmCpeTable(void);

#if defined(__cplusplus)
extern "C"
{
#endif  //#if defined(__cplusplus)

Netsnmp_Node_Handler      GsAnCmcCmCpeHandler;
Netsnmp_First_Data_Point  GsAnCmcCmCpeGetFirst;
Netsnmp_Next_Data_Point   GsAnCmcCmCpeGetNext;

/* column number definitions for table gsAnCmcCmCpeTable */
#define ColumnCmIndex       1
#define ColumnCpeIndex      2
#define ColumnCmMacAddr     3
#define ColumnCpeMacAddr    4
#define ColumnCpeIpAddrType 5
#define ColumnCpeIpAddr     6
#define ColumnCpeType       7

#if defined(__cplusplus)
}
#endif  //#if defined(__cplusplus)
       
#endif /* GSANCMCCMCPETABLE_H */
