/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef GSANCMCCMSTATISTICS_H
#define GSANCMCCMSTATISTICS_H

/* function declarations */
void InitGsAnCmcCmStatistics(void);


#if defined(__cplusplus)
           extern "C"
           {
#endif  //#if defined(__cplusplus)

Netsnmp_Node_Handler handle_gsAnCmcCmTotal;
Netsnmp_Node_Handler handle_gsAnCmcCmActive;
Netsnmp_Node_Handler handle_gsAnCmcCmOnline;
Netsnmp_Node_Handler handle_gsAnCmcCmOffline;
Netsnmp_Node_Handler handle_gsAnCmcCmInitR;
Netsnmp_Node_Handler handle_gsAnCmcCmRC;
Netsnmp_Node_Handler handle_gsAnCmcCmDHCPDiscover;
Netsnmp_Node_Handler handle_gsAnCmcCmDHCPOffer;
Netsnmp_Node_Handler handle_gsAnCmcCmDHCPRequest;
Netsnmp_Node_Handler handle_gsAnCmcCmDHCPAck;
Netsnmp_Node_Handler handle_gsAnCmcCmInitF;
Netsnmp_Node_Handler handle_gsAnCmcCmFC;
Netsnmp_Node_Handler handle_gsAnCmcCmInitREG;
       
#if defined(__cplusplus)
          }
#endif  //#if defined(__cplusplus)

#endif /* GSANCMCCMSTATISTICS_H */
