/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17695 2009-07-21 12:22:18Z dts12 $
 */
#ifndef _gsCableDocsLoadBalGrpCfgTable_h_
#define _gsCableDocsLoadBalGrpCfgTable_h_

void InitDocsLoadBalGrpCfgTable(void);

#if defined(__cplusplus)
extern "C"
{
#endif  //#if defined(__cplusplus)

/*
 * function declarations..
 */
Netsnmp_Node_Handler      DocsLoadBalGrpCfgHandler;

Netsnmp_First_Data_Point  DocsLoadBalGrpCfgGetFirst;
Netsnmp_Next_Data_Point   DocsLoadBalGrpCfgGetNext;

/* column number definitions for table gsCableDocsLoadBalGrpCfgTable */
#define ColumnGsCableDocsLoadBalGrpCfgId             1
#define ColumnGsCableDocsLoadBalGrpCfgType           2
#define ColumnGsCableDocsLoadBalGrpCfgDsChList       3
#define ColumnGsCableDocsLoadBalGrpCfgUsChList       4
#define ColumnGsCableDocsLoadBalGrpCfgActiveMacAddr  5
#define ColumnGsCableDocsLoadBalGrpCfgOption         6

/* Row Status */
#define RowStatusCreate  1
#define RowStatusDestroy 2

#if defined(__cplusplus)
}
#endif  //#if defined(__cplusplus)

#endif /* _gsCableDocsLoadBalGrpCfgTable_h_ */
