/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17695 2009-07-21 12:22:18Z dts12 $
 */
#ifndef _gsDslSyslogHostTable_h_
#define _gsDslSyslogHostTable_h_

namespace Snmp
{
namespace gsDslSyslogHostTable
{

/* function declarations */
void InitGsDslSyslogHostTable(void);

int SnmpTableHandler(netsnmp_mib_handler *handler,
    netsnmp_handler_registration *regInfo,
    netsnmp_agent_request_info *reqInfo,
    netsnmp_request_info *requests);

Netsnmp_First_Data_Point  GetFirst;
Netsnmp_Next_Data_Point   GetNext;
Netsnmp_Free_Data_Context FreeData;
Netsnmp_Free_Loop_Context FreeLoopAtEnd;

/* column number definitions for table gsDslSyslogHostTable */
#define ColGsDslSsyslogHostIpAddr       1
#define ColGsDslSyslogDesPort           2
#define ColGsDslSyslogHostRowStatus     10

}
}

#endif /* _gsDslSyslogHostTable_h_ */
