/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17695 2009-07-21 12:22:18Z dts12 $
 */
#ifndef _gsCableDocsLoadBalMacRangeCfgTable_h_
#define _gsCableDocsLoadBalMacRangeCfgTable_h_

void InitDocsLoadBalMacRangeCfgTable(void);

#if defined(__cplusplus)
extern "C"
{
#endif  //#if defined(__cplusplus)

/*
 * function declarations..
 */
Netsnmp_Node_Handler      DocsLoadBalMacRangeCfgHandler;

Netsnmp_First_Data_Point  DocsLoadBalMacRangeCfgGetFirst;
Netsnmp_Next_Data_Point   DocsLoadBalMacRangeCfgGetNext;

#define ColumnGsCableDocsLoadBalMacRangeGrpCfgId        1
#define ColumnGsCableDocsLoadBalMacRangeCfgIndex     2
#define ColumnGsCableDocsLoadBalMacRangeCfgStartMac   3
#define ColumnGsCableDocsLoadBalMacRangeCfgEndMac    4
#define ColumnGsCableDocsLoadBalMacRangeCfgOption    5

/* Row Status */
#define RowStatusCreate  1
#define RowStatusDestroy 2

#if defined(__cplusplus)
}
#endif  //#if defined(__cplusplus)

#endif /* _gsCableDocsLoadBalMacRangeCfgTable_h_ */
