/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef _gsAnCmcGlobalObject_h_
#define _gsAnCmcGlobalObject_h_

namespace Snmp
{
namespace GsAnCmcGlobalObject
{

/* function declarations */
void InitGsAnCmcGlobalObject(void);
Netsnmp_Node_Handler HandleCmcUpstreamErrorRateThreshold;
Netsnmp_Node_Handler HandleCmcCmMacAddress;
Netsnmp_Node_Handler HandleCmcUpstreamSnrThreshold;
Netsnmp_Node_Handler HandleCmcMaxCmThreshold;
Netsnmp_Node_Handler HandleCmcCmNumber;
Netsnmp_Node_Handler HandleCmcDdosAttackType;
Netsnmp_Node_Handler HandleCmcAllCmResetNow;
Netsnmp_Node_Handler HandleCmcAllCmDeleteNow;

}
}
#endif /* _gsAnCmcGlobalObject_h_ */
