/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef GSANCMCSYSTEM_H
#define GSANCMCSYSTEM_H

/* function declarations */
void InitGsAnCmcSystem(void);

#define ChannelBindEnable 1
#define ChannelBindDisable 0

#define UsUsaStd 1
#define UsEuroStd 2
#define AllUsChannel 0

#define DsUsaStd 1
#define DsEuroStd 2
#define AllDsChannel 0

Netsnmp_Node_Handler HandleCmcChannelBinding;
Netsnmp_Node_Handler HandleCmcUpFrequencyStandard;
Netsnmp_Node_Handler HandleCmcDownFrequencyStandard;    
      
#endif /* GSANCMCSYSTEM_H */
