/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef GSANCMCCHANNELSTATISTICSTABLE_H
#define GSANCMCCHANNELSTATISTICSTABLE_H

/* function declarations */
void InitGsAnCmcChannelStatisticsTable(void);
       
Netsnmp_Node_Handler CmcChannelStatisticsTableHandler;
Netsnmp_First_Data_Point ChannelStatisticsTableGetFirst;
Netsnmp_Next_Data_Point ChannelStatisticsTableGetNext;
   
/* column number definitions for table gsAnCmcChannelStatisticsTable */
#define ColChannelStaticsIndex 1
#define ColChannelStaticsIfIndex	2
#define ColChannelStaticsDir 3
#define ColChannelStaticsId 4
#define ColChannelStaticsName 5
#define ColChannelStaticsSpeed 6
#define ColChannelStaticsWidth 7
#define ColChannelStaticsUtilization 8
              
       
#endif /* GSANCMCCHANNELSTATISTICSTABLE_H */
