/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17695 2009-07-21 12:22:18Z dts12 $
 */
#ifndef _gsCableDocsDsQosCfgTable_h_
#define _gsCableDocsDsQosCfgTable_h_

CxxBeginNameSpace(Snmp)
CxxBeginNameSpace(GsCableDocsDsQosCfgTable)

/* function declarations */
void InitTable(void);

Netsnmp_Node_Handler SnmpNodeHandler;
Netsnmp_First_Data_Point  GetFirst;
Netsnmp_Next_Data_Point   GetNext;

/* column number definitions for table gsCableDocsDsQosCfgTable */
#define ColumnMac          1
#define ColumnWidth        2
#define ColumnOption       32

#define RowStatusCreate  1
#define RowStatusDestroy 2

CxxEndNameSpace /* Snmp */
CxxEndNameSpace /* GsCableDocsDsQosCfgTable */

#endif /* _gsCableDocsDsQosCfgTable_h_ */
