/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17695 2009-07-21 12:22:18Z dts12 $
 */
#ifndef _gsCableDocsLoadBalExcludeMacCfgTable_h_
#define _gsCableDocsLoadBalExcludeMacCfgTable_h_

void InitDocsLoadBalExcludeMacCfgTable(void);

#if defined(__cplusplus)
extern "C"
{
#endif  //#if defined(__cplusplus)

/*
 * function declarations..
 */
Netsnmp_Node_Handler      DocsLoadBalExcludeMacCfgHandler;

Netsnmp_First_Data_Point  DocsLoadBalExcludeMacCfgGetFirst;
Netsnmp_Next_Data_Point   DocsLoadBalExcludeMacCfgGetNext;

#define ColumnGsCableDocsLoadBalExcludeMacCfgIndex    1
#define ColumnGsCableDocsLoadBalExcludeMacCfgStartMac 2
#define ColumnGsCableDocsLoadBalExcludeMacCfgEndMac   3
#define ColumnGsCableDocsLoadBalExcludeMacCfgOption   4

/* Row Status */
#define RowStatusCreate  1
#define RowStatusDestroy 2

#if defined(__cplusplus)
}
#endif  //#if defined(__cplusplus)

#endif /* _gsCableDocsLoadBalMacRangeCfgTable_h_ */
