/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17695 2009-07-21 12:22:18Z dts12 $
 */
#include "SystemInclude.h"
#include "BcmController.h"

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "Debug.h"
#include "LoadBalanceMgt.h"
#include "gsCableDocsLoadBalExcludeMacCfgTable.h"
using namespace std;

typedef int(*SnmpOperationHandler)(netsnmp_mib_handler*,
                                   netsnmp_handler_registration*,
                                   netsnmp_agent_request_info*,
                                   netsnmp_request_info*);

static int DocsLoadBalExcludeMacCfgGet(netsnmp_mib_handler*,
                                       netsnmp_handler_registration*,
                                       netsnmp_agent_request_info*,
                                       netsnmp_request_info*);
static int DocsLoadBalExcludeMacCfgSetReserve1(netsnmp_mib_handler*,
                                               netsnmp_handler_registration*,
                                               netsnmp_agent_request_info*,
                                               netsnmp_request_info*);
static int DocsLoadBalExcludeMacCfgSetReserve2(netsnmp_mib_handler*,
                                               netsnmp_handler_registration*,
                                               netsnmp_agent_request_info*,
                                               netsnmp_request_info*);
static int DocsLoadBalExcludeMacCfgSetFree(netsnmp_mib_handler*,
                                           netsnmp_handler_registration*,
                                           netsnmp_agent_request_info*,
                                           netsnmp_request_info*);
static int DocsLoadBalExcludeMacCfgSetAction(netsnmp_mib_handler*,
                                             netsnmp_handler_registration*,
                                             netsnmp_agent_request_info*,
                                             netsnmp_request_info*);
static int DocsLoadBalExcludeMacCfgSetUndo(netsnmp_mib_handler*,
                                           netsnmp_handler_registration*,
                                           netsnmp_agent_request_info*,
                                           netsnmp_request_info*);
static int DocsLoadBalExcludeMacCfgSetCommit(netsnmp_mib_handler*,
                                             netsnmp_handler_registration*,
                                             netsnmp_agent_request_info*,
                                             netsnmp_request_info*);

typedef void(*SnmpSetValueToPktHandler)(netsnmp_agent_request_info*,
                                        netsnmp_request_info*,
                                        int32_t);

static void SnmpSetValueToReqestIndex(netsnmp_agent_request_info *reqInfo,
                                      netsnmp_request_info       *request,
                                      int32_t                    index);
static void SnmpSetValueToReqestStartMac(netsnmp_agent_request_info *reqInfo,
                                         netsnmp_request_info       *request,
                                         int32_t                    index);
static void SnmpSetValueToReqestEndMac(netsnmp_agent_request_info *reqInfo,
                                       netsnmp_request_info       *request,
                                       int32_t                    index);
static void SnmpSetValueToReqestOption(netsnmp_agent_request_info *reqInfo,
                                       netsnmp_request_info       *request,
                                       int32_t                    index);

static map<int, SnmpOperationHandler> snmpHandler;
static map<int, SnmpSetValueToPktHandler>  snmpSetValueHandler;

#define MacRangeStartIndex 1

/** Initializes the docsIfDownstreamChannelTable module */
void InitDocsLoadBalExcludeMacCfgTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    const oid    tableOid[] = {1,3,6,1,4,1,22764,1015,9026,2,4,4};
    const size_t oidLen     = OID_LENGTH(tableOid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;

    reg = netsnmp_create_handler_registration("gsCableDocsLoadBalExcludeMacCfgTable",
                                              DocsLoadBalExcludeMacCfgHandler,
                                              tableOid, oidLen,
                                              HANDLER_CAN_RWRITE);

    netsnmp_table_registration_info *tableInfo;
    tableInfo = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(tableInfo,
                                     ASN_INTEGER,  /* index */
                                     0);
    tableInfo->min_column = ColumnGsCableDocsLoadBalExcludeMacCfgIndex;
    tableInfo->max_column = ColumnGsCableDocsLoadBalExcludeMacCfgOption;

    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = DocsLoadBalExcludeMacCfgGetFirst;
    iinfo->get_next_data_point  = DocsLoadBalExcludeMacCfgGetNext;
    iinfo->table_reginfo        = tableInfo;

    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialize the contents of the table here */
    snmpHandler.insert(make_pair(MODE_GET, DocsLoadBalExcludeMacCfgGet));
    snmpHandler.insert(make_pair(MODE_SET_RESERVE1, DocsLoadBalExcludeMacCfgSetReserve1));
    snmpHandler.insert(make_pair(MODE_SET_RESERVE2, DocsLoadBalExcludeMacCfgSetReserve2));
    snmpHandler.insert(make_pair(MODE_SET_FREE, DocsLoadBalExcludeMacCfgSetFree));
    snmpHandler.insert(make_pair(MODE_SET_ACTION, DocsLoadBalExcludeMacCfgSetAction));
    snmpHandler.insert(make_pair(MODE_SET_UNDO, DocsLoadBalExcludeMacCfgSetUndo));
    snmpHandler.insert(make_pair(MODE_SET_COMMIT, DocsLoadBalExcludeMacCfgSetCommit));

    snmpSetValueHandler.insert(make_pair(ColumnGsCableDocsLoadBalExcludeMacCfgIndex, SnmpSetValueToReqestIndex));
    snmpSetValueHandler.insert(make_pair(ColumnGsCableDocsLoadBalExcludeMacCfgStartMac, SnmpSetValueToReqestStartMac));
    snmpSetValueHandler.insert(make_pair(ColumnGsCableDocsLoadBalExcludeMacCfgEndMac, SnmpSetValueToReqestEndMac));
    snmpSetValueHandler.insert(make_pair(ColumnGsCableDocsLoadBalExcludeMacCfgOption, SnmpSetValueToReqestOption));
}

/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list* DocsLoadBalExcludeMacCfgGetFirst(void **loopContext,
                                                        void **dataContext,
                                                        netsnmp_variable_list *indexData,
                                                        netsnmp_iterator_info *data)
{
    BASE_ErrCode   errCode;
    dbgstrm << "Start." << endl;

    CnuExecludeMacRangeCfgT range;
    errCode = GetFirstCnuExcludeMacRange(&range, cliGetCmc());
    if (errCode != BASE_OK)
    {
        dbgstrm << "No exclude MAC range." << endl;
        *dataContext = NULL;
        *loopContext = NULL;
        return NULL;
    }

    snmp_set_var_value(indexData, &range.index, sizeof(int32_t));
    *dataContext = (void *)range.index;
    *loopContext = (void *)range.index;
    return indexData;
}

/* The GetNext() function is called by net-snmp library to iterate all table index,
 * terminate loop by return NULL.
 */
netsnmp_variable_list* DocsLoadBalExcludeMacCfgGetNext(void **loopContext,
                                                       void **dataContext,
                                                       netsnmp_variable_list *indexData,
                                                       netsnmp_iterator_info *data)
{
    BASE_ErrCode errCode;

    dbgstrm << "Start." << endl;
    int32_t index = (int32_t)(*loopContext);
    CnuExecludeMacRangeCfgT range;

    errCode = GetNextCnuExcludeMacRange(index, &range, cliGetCmc());
    if (errCode == BASE_OK)
    {
        dbgstrm << "No next exclude MAC range." << endl;
        snmp_set_var_value(indexData, &range.index, sizeof(int32_t));

        *dataContext = (void *)range.index;
        *loopContext = (void *)range.index;

        return indexData;
    }

    *dataContext = NULL;
    *loopContext = NULL;
    return NULL;
}

void SnmpSetValueToReqestIndex(netsnmp_agent_request_info *reqInfo,
                               netsnmp_request_info       *request,
                               int32_t                    index)
{
    dbgstrm << "Start." << endl;
    snmp_set_var_typed_value(request->requestvb, ASN_INTEGER,
                             &index, sizeof(int32_t));
}

void SnmpSetValueToReqestStartMac(netsnmp_agent_request_info *reqInfo,
                                  netsnmp_request_info       *request,
                                  int32_t                    index)
{
    CnuExecludeMacRangeCfgT range;
    BASE_ErrCode errCode = FindCnuExcludeMacRange(index, &range, cliGetCmc());
    if (errCode != BASE_OK)
    {
        netsnmp_set_request_error(reqInfo, request, SNMP_NOSUCHINSTANCE);
        return;
    }

    snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                             range.macRange.start,
                             6);
}

void SnmpSetValueToReqestEndMac(netsnmp_agent_request_info *reqInfo,
                                  netsnmp_request_info       *request,
                                  int32_t                    index)
{
    CnuExecludeMacRangeCfgT range;
    BASE_ErrCode errCode = FindCnuExcludeMacRange(index, &range, cliGetCmc());
    if (errCode != BASE_OK)
    {
        netsnmp_set_request_error(reqInfo, request, SNMP_NOSUCHINSTANCE);
        return;
    }

    snmp_set_var_typed_value(request->requestvb, ASN_OCTET_STR,
                             range.macRange.end,
                             6);
}

void SnmpSetValueToReqestOption(netsnmp_agent_request_info *reqInfo,
                                netsnmp_request_info       *request,
                                int32_t                    index)
{
    int32_t option = 0;
    snmp_set_var_typed_value(request->requestvb, ASN_INTEGER,
                             &option, sizeof(int32_t));
}

int DocsLoadBalExcludeMacCfgGet(netsnmp_mib_handler               *handler,
                              netsnmp_handler_registration      *regInfo,
                              netsnmp_agent_request_info        *reqInfo,
                              netsnmp_request_info              *requests)
{
    netsnmp_request_info       *request;
    netsnmp_table_request_info *tableInfo;

    dbgstrm << "Start." << endl;
    for (request=requests; request; request=request->next)
    {
        int32_t index = (int32_t)netsnmp_extract_iterator_context(request);
        dbgstrm << "index = " << index << endl;

        if ((void *)index == NULL)
        {
            dbgstrm << "entry is NULL" << endl;
            netsnmp_set_request_error(reqInfo, request, SNMP_NOSUCHINSTANCE);
            continue;
        }
        tableInfo  = netsnmp_extract_table_info(request);

        map<int, SnmpSetValueToPktHandler>::iterator iter;
        iter = snmpSetValueHandler.find(tableInfo->colnum);
        if(iter != snmpSetValueHandler.end())
        {
            iter->second(reqInfo, requests, index);
        }
        else
        {
            dbgstrm << "Error, wrong table column number";
            netsnmp_set_request_error(reqInfo, request, SNMP_NOSUCHINSTANCE);
        }
    }

    return SNMP_ERR_NOERROR;
}

int DocsLoadBalExcludeMacCfgSetReserve1(netsnmp_mib_handler               *handler,
                                      netsnmp_handler_registration      *regInfo,
                                      netsnmp_agent_request_info        *reqInfo,
                                      netsnmp_request_info              *requests)
{
    dbgstrm << "Start." << endl;
    return SNMP_ERR_NOERROR;
}

/* MODE_SET_RESERVE2:
 *    When create new entry, this function allocate resource for new entry.
 *    When modify or query entry,  do nothing.
 * Refer to net-snmp example codes "mteTriggerTable.c" for "mteTriggerTable"
 * of DISMAN-EVENT-MIB.
 */
int DocsLoadBalExcludeMacCfgSetReserve2(netsnmp_mib_handler               *handler,
                                      netsnmp_handler_registration      *regInfo,
                                      netsnmp_agent_request_info        *reqInfo,
                                      netsnmp_request_info              *requests)
{
    netsnmp_request_info       *request;
    netsnmp_table_request_info *tableInfo;

    BASE_ErrCode errCode;
    MacAddressT mac = {{0xff, 0xff, 0xff, 0xff, 0xff, 0xff}};

    dbgstrm << "Start." << endl;
    for (request = requests; request; request = request->next)
    {
        int32_t index;

        tableInfo = netsnmp_extract_table_info(request);
        switch(tableInfo->colnum)
        {
        case ColumnGsCableDocsLoadBalExcludeMacCfgOption:
            /*
             * Create an (empty) new row structure
             */
            switch (*request->requestvb->val.integer)
            {
            case RowStatusCreate:
                /* Note: this index is not content of table.  It is the "Instance" field
                 *       in MIB-Browser.
                 */
                errCode = AddCnuExcludeRange(&mac, &mac, cliGetCmc());
                if (errCode != BASE_OK)
                {
                    cerr << "Can't create MAC range, index = " << index << endl;
                    netsnmp_set_request_error(reqInfo, request, SNMP_ERR_BADVALUE);
                    return SNMP_ERR_NOERROR;
                }

                index = GetCnuMacExcludeRangeSize(cliGetCmc());
                netsnmp_insert_iterator_context(request, (void *)index);
                break;

            default:
                break;
            }
            break;

        default:
            break;
        }
    }
    return SNMP_ERR_NOERROR;
}

int DocsLoadBalExcludeMacCfgSetFree(netsnmp_mib_handler               *handler,
                                  netsnmp_handler_registration      *regInfo,
                                  netsnmp_agent_request_info        *reqInfo,
                                  netsnmp_request_info              *requests)
{
    dbgstrm << "Start." << endl;
    return SNMP_ERR_NOERROR;
}

/*
 * When modify table,  the program flow is:
 *      SetReserve1()
 *      SetReserve2()
 *      SetAction()
 *      SetCommit()
 * net-snmp will call this function for every modification separately,
 * so we can't commit once for all modification, we can only call
 * SetFullLoadBalancingGrp() immediately for every field in requests loop.
 */
int DocsLoadBalExcludeMacCfgSetCommit(netsnmp_mib_handler               *handler,
                                    netsnmp_handler_registration      *regInfo,
                                    netsnmp_agent_request_info        *reqInfo,
                                    netsnmp_request_info              *requests)
{
    netsnmp_request_info       *request;
    netsnmp_table_request_info *tableInfo;

    dbgstrm << "Start." << endl;
    for (request=requests; request; request=request->next)
    {
        int32_t index = (int32_t)netsnmp_extract_iterator_context(request);

        dbgstrm << "index = " << index << endl;
        CnuExecludeMacRangeCfgT range;
        MacAddressT start, end;
        BASE_ErrCode errCode = FindCnuExcludeMacRange(index, &range, cliGetCmc());
        if (errCode != BASE_OK)
        {
            netsnmp_set_request_error(reqInfo, request, SNMP_NOSUCHINSTANCE);
            break;
        }

        tableInfo = netsnmp_extract_table_info(request);

        switch (tableInfo->colnum)
        {
         case ColumnGsCableDocsLoadBalExcludeMacCfgIndex:
            dbgstrm << index << endl;
            break;

        case ColumnGsCableDocsLoadBalExcludeMacCfgStartMac:
            memcpy(range.macRange.start,
                   request->requestvb->val.string, 6);
            errCode = UpdateCnuExcludeMacRange(&range, cliGetCmc());
            break;

        case ColumnGsCableDocsLoadBalExcludeMacCfgEndMac:
            memcpy(range.macRange.end,
                   request->requestvb->val.string, 6);
            errCode = UpdateCnuExcludeMacRange(&range, cliGetCmc());
            break;

        case ColumnGsCableDocsLoadBalExcludeMacCfgOption:
            switch (*request->requestvb->val.integer)
            {
            case RowStatusDestroy:
                /* Note: this index is not content of table.  It is the "Instance" field
                 *       in MIB-Browser.
                 */
                memcpy(start.addr, range.macRange.start, 6);
                memcpy(end.addr, range.macRange.end, 6);
                errCode = RemoveCnuExcludeRange(&start, &end, cliGetCmc());
                break;

            default:
                break;
            }
            break;

        default:
            break;
        }

        if (errCode != BASE_OK)
        {
            netsnmp_set_request_error(reqInfo, request, SNMP_ERR_BADVALUE);
            break;
        }
    }
    return SNMP_ERR_NOERROR;
}

int DocsLoadBalExcludeMacCfgSetAction(netsnmp_mib_handler               *handler,
                                    netsnmp_handler_registration      *regInfo,
                                    netsnmp_agent_request_info        *reqInfo,
                                    netsnmp_request_info              *requests)
{
    dbgstrm << "Start." << endl;
    return SNMP_ERR_NOERROR;
}

int DocsLoadBalExcludeMacCfgSetUndo(netsnmp_mib_handler               *handler,
                                  netsnmp_handler_registration      *regInfo,
                                  netsnmp_agent_request_info        *reqInfo,
                                  netsnmp_request_info              *requests)
{
    dbgstrm << "Start." << endl;
    return SNMP_ERR_NOERROR;
}

/** handles requests for the netSnmpIETFWGTable table */
int DocsLoadBalExcludeMacCfgHandler(netsnmp_mib_handler               *handler,
                                  netsnmp_handler_registration      *regInfo,
                                  netsnmp_agent_request_info        *reqInfo,
                                  netsnmp_request_info              *requests)
{
    map<int, SnmpOperationHandler>::iterator iter;
    iter = snmpHandler.find(reqInfo->mode);
    assert(iter != snmpHandler.end());
    iter->second(handler, regInfo, reqInfo, requests);

    return SNMP_ERR_NOERROR;
}
