/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef GSANCMCCDTTRANSSVIDTABLE_H
#define GSANCMCCDTTRANSSVIDTABLE_H

/* function declarations */
void InitGsAnCmcCdtTransSVidTable(void);

/* column number definitions for table gsAnCmcCdtTransSVidTable */
#define ColCmcCdtCos 1
#define ColCmcCdtTransSVid	 2
#define ColCmcCdtTransSVidRowStatus 50
       
Netsnmp_Node_Handler CmcCdtTransSVidTableHandler;
Netsnmp_First_Data_Point CmcCdtTransSVidTableGetFirst;
Netsnmp_Next_Data_Point CmcCdtTransSVidTableGetNext;
       
#endif /* GSANCMCCDTTRANSSVIDTABLE_H */
