WorkspaceRoot=$(shell FindRootPath.sh $(CURDIR))
include $(WorkspaceRoot)/Make/Make.Configuration

SubDirs = gsCableDocsServiceFlowCfgTable gsCableDocsDsQosCfgTable 

all: $(SubDirs)
include $(WorkspaceRoot)/Make/Make.SubDirs

