/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate.conf 17827 2009-11-20 16:18:11Z bvassche $
 */

#ifndef _docsIfUpstreamChannelTable_h_
#define _docsIfUpstreamChannelTable_h_

void InitDocsIfUpChannelTable(void);

#if defined(__cplusplus)
extern "C"
{
#endif  //#if defined(__cplusplus) 

/*
 * function declarations..
 */
Netsnmp_Node_Handler      DocsIfUpChannelHandler;

Netsnmp_First_Data_Point  DocsIfUpChannelGetFirst;
Netsnmp_Next_Data_Point   DocsIfUpChannelGetNext;

#define ColumnDocsIfUpChannelId                1
#define ColumnDocsIFUpChannelFrequency         2
#define ColumnDocsIfUpChannelWidth             3
#define ColumnDocsIfUpChannelModulationProfile 4
#define ColumnDocsIfUpChannelSlotSize          5
#define ColumnDocsIfUpChannelTxTimingOffset    6
#define ColumnDocsIfUpChannelRangingBackoffStart    7
#define ColumnDocsIfUpChannelRangingBackOffend      8
#define ColumnDocsIfUpChannelTxBackoffStart    9
#define ColumnDocsIfUpChannelTxBackoffEnd      10
#define ColumnDocsIfUpChannelScdmaActivecodes  11
#define ColumnDocsIfUpChannelScdmaCodesperSlot 12
#define ColumnDocsIfUpChannelScdmaFrameSize    13
#define ColumnDocsIfUpChannelScdmaHoppingSeed  14
#define ColumnDocsIfUpChannelType              15
#define ColumnDocsIfUpChannelCloneFrom         16
#define ColumnDocsIfUpChannelUpDate            17
#define ColumnDocsIfUpChannelStatus            18
#define ColumnDocsIfUpChannelPreeqEnable       19

#if defined(__cplusplus)
}
#endif  //#if defined(__cplusplus)

#endif /** _docsIfUpstreamChannelTable_h_ */

