WorkspaceRoot=$(shell FindRootPath.sh $(CURDIR))
include $(WorkspaceRoot)/Make/Make.Configuration

SubDirs = gsDslSysctrlObjects gsDslSysctrlTrapObjects

all: $(SubDirs)
include $(WorkspaceRoot)/Make/Make.SubDirs

