--- Src/src/bcm93380/kernel/linux/Makefile	2013-12-08 21:45:31.000000000 -0800
+++ Src/src/bcm93380/kernel/linux/Makefile.new	2014-09-08 20:37:23.393313000 -0700
@@ -353,7 +353,7 @@
 KBUILD_CFLAGS   := -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs \
 		   -fno-strict-aliasing -fno-common \
 		   -Werror-implicit-function-declaration
-KBUILD_CFLAGS	+= -Wno-unused-but-set-variable
+#KBUILD_CFLAGS	+= -Wno-unused-but-set-variable
 KBUILD_AFLAGS   := -D__ASSEMBLY__
 
 # Read KERNELRELEASE from include/config/kernel.release (if it exists)
