/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 17337 2009-01-01 14:28:29Z magfr $
 */
#ifndef _gsDslCommon_h_
#define _gsDslCommon_h_

/* function declarations */
void InitGsDslCommon(void);

Netsnmp_Node_Handler HandleGsDslCliPrompt;
Netsnmp_Node_Handler HandleGsDslLineTestRootMode;
Netsnmp_Node_Handler HandleGsDslEPMConfType;
Netsnmp_Node_Handler HandleGsDslSaveToNvm;
Netsnmp_Node_Handler HandleGsDslEraseNvm;
Netsnmp_Node_Handler HandleGsDslSwapCore;
Netsnmp_Node_Handler HandleGsDslBorrowBoardSet;
Netsnmp_Node_Handler HandleGsDslBorrowBoardGet;
Netsnmp_Node_Handler HandleGsDslSysDateTime;
Netsnmp_Node_Handler HandleGsDslTimeZoneOffset;
Netsnmp_Node_Handler HandleGsDslIsHalfTimeZone;
Netsnmp_Node_Handler HandleGsDslSystemReboot;
Netsnmp_Node_Handler HandleGsDslSystemPortList;
Netsnmp_Node_Handler HandleGsDslAutoSaveToNvmInterval;
Netsnmp_Node_Handler HandleGsDslTimingSaveModifiedToNvmInterval;
Netsnmp_Node_Handler HandleGsDslTimingSaveToNvmInterval;
Netsnmp_Node_Handler HandleGsDslUserSideMtu;
Netsnmp_Node_Handler HandleGsDslSysMaxPortNumPerSlot;
Netsnmp_Node_Handler HandleGsDslSysOutbandPortUsage;
Netsnmp_Node_Handler HandleGsDslSysDebugUserEnable;
Netsnmp_Node_Handler HandleGsDslSerialPortBaudRate;

#endif /* _gsDslCommon_h_ */
