/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef GSANCMCVENDORTOVLANOBJECTS_H
#define GSANCMCVENDORTOVLANOBJECTS_H

/* function declarations */
void InitGsAnCmcVendorToVlanObjects(void);

Netsnmp_Node_Handler HandleCmcVendorToVlanStatus;

#endif /* GSANCMCVENDORTOVLANOBJECTS_H */
