/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 17337 2009-01-01 14:28:29Z magfr $
 */
#ifndef _ifTable_h_
#define _ifTable_h_

CxxBeginNameSpace(Snmp)
CxxBeginNameSpace(Interfaces)

/* function declarations */
void InitIfTable(void);

Netsnmp_Node_Handler      SnmpNodeHandler;
Netsnmp_First_Data_Point  GetFirst;
Netsnmp_Next_Data_Point   GetNext;

/* column number definitions for table ifTable */
#define ColumnIfIndex              1
#define ColumnIfDescr              2
#define ColumnIfType               3
#define ColumnIfMtu                4
#define ColumnIfSpeed              5
#define ColumnIfPhysAddress        6
#define ColumnIfAdminStatus        7
#define ColumnIfOperStatus         8
#define ColumnIfLastChange         9
#define ColumnIfInOctets           10
#define ColumnIfInUcastPkts        11
#define ColumnIfInNUcastPkts       12
#define ColumnIfInDiscards         13
#define ColumnIfInErrors           14
#define ColumnIfInUnknownProtos    15
#define ColumnIfOutOctets          16
#define ColumnIfOutUcastpkts       17
#define ColumnIfOutNUcastPkts      18
#define ColumnIfOutDiscards        19
#define ColumnIfOutErrors          20
#define ColumnIfOutQLen            21
#define ColumnIfSpecific           22

CxxEndNameSpace /* Interfaces */
CxxEndNameSpace /* Snmp */

#endif /* _ifTable_h_ */
