/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 17337 2009-01-01 14:28:29Z magfr $
 */
#ifndef _interfaces_h_
#define _interfaces_h_

CxxBeginNameSpace(Snmp)
CxxBeginNameSpace(Interfaces)

/* function declarations */
void InitInterfaces(void);

Netsnmp_Node_Handler HandleIfNumber;

CxxEndNameSpace /* Interfaces */
CxxEndNameSpace /* Snmp */

#endif /* _interfaces_h_ */
