WorkspaceRoot=$(shell FindRootPath.sh $(CURDIR))
include $(WorkspaceRoot)/Make/Make.Configuration

#gsCableDocsUsSpectrumChartTable
SubDirs = gsCableDocsUsSpectrumSystem  \
           
		   
all: $(SubDirs)
include $(WorkspaceRoot)/Make/Make.SubDirs

