/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.iterate.conf 17695 2009-07-21 12:22:18Z dts12 $
 */
#ifndef _gsDslTrapHostTable_h_
#define _gsDslTrapHostTable_h_

namespace Snmp
{
namespace GsDslTrapHostTable
{
/* function declarations */
void InitGsDslTrapHostTable(void);

int SnmpTableHandler(netsnmp_mib_handler *handler,
    netsnmp_handler_registration *regInfo,
    netsnmp_agent_request_info *reqInfo,
    netsnmp_request_info *requests);

Netsnmp_First_Data_Point  GetFirst;
Netsnmp_Next_Data_Point   GetNext;

/* column number definitions for table gsDslTrapHostTable */
#define ColGsDslTrapHostIpAddr          1
#define ColGsDslTrapHostSnmpVer         2
#define ColGsDslTrapHostCommunity       3
#define ColGsDslTrapHostIsGosNmsServer  4
#define ColGsDslTrapHostRowStatus       5
#define ColGsDslTrapHostEventType       6
#define ColGsDslTrapHostMinEventLevel   7

} /* namespace GsDslTrapHostTable*/
} /* namespace Snmp*/

#endif /* _gsDslTrapHostTable_h_ */
