/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef GSANCMCPORTSTATISTICSTABLE_H
#define GSANCMCPORTSTATISTICSTABLE_H

/* function declarations */
void InitGsAnCmcPortStatisticsTable(void);

Netsnmp_Node_Handler CmcPortStatisticsTableHandler;
Netsnmp_First_Data_Point CmcPortStatisticsTableGetFirst;
Netsnmp_Next_Data_Point CmcPortStatisticsTableGetNext;

/* column number definitions for table gsAnCmcChannelStatisticsTable */
#define ColPortIndex 1
#define ColPortIndexRxSpeed 2
#define ColPortIndexTxSpeed 3
   
#endif /* GSANCMCPORTSTATISTICSTABLE_H */
