/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 17337 2009-01-01 14:28:29Z magfr $
 */
#ifndef _gsDslDhcpRelay_h_
#define _gsDslDhcpRelay_h_

CxxBeginNameSpace(Snmp)
CxxBeginNameSpace(GsDslDhcpRelay)

/* function declarations */
void InitGsDslDhcpRelay(void);
Netsnmp_Node_Handler HandleDhcpServerAddress;

CxxEndNameSpace /* GsDslDhcpRelay */
CxxEndNameSpace /* Snmp */

#endif /* GSDSLDHCPRELAY_H */
